# Generated by Django 4.1.5 on 2023-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название места', max_length=255, verbose_name='Место')),
                ('description_short', models.CharField(help_text='Введите короткое описание', max_length=255, verbose_name='Короткое описание')),
                ('description_long', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
