# Generated by Django 4.1.5 on 2023-02-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_photo_options_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(help_text='Введите название места', max_length=255, unique=True, verbose_name='Место'),
        ),
    ]
