# Generated by Django 4.1.5 on 2023-02-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_photo_number_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place'),
        ),
    ]
