# Generated by Django 4.1.5 on 2023-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(max_length=20),
        ),
    ]
