# Generated by Django 4.1.5 on 2023-02-09 06:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_photo_image_alter_place_lat_alter_place_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Введите описание', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Введите короткое описание', max_length=255, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
