# Generated by Django 4.1.5 on 2023-02-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place'),
            preserve_default=False,
        ),
    ]
