# Generated by Django 4.1.5 on 2023-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_photo_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
